language: node_js
git:
  depth: 1
node_js:
- stable
env:
  global:
  - GITHUB_REPO: cshtdd/supplement-facts
  - BRANCH_TO_MERGE_INTO: gh-pages
  - secure: f9L1GQ0bQXMQfgZw2NBFbN/zJSiRmOYp1TFkqUjQLPbsothK82g8dYo7VkYaXYyx9/+kc9l67KNkknE0O3ht8Z8tHrzjqtdd0vonWhlYnt03Adyyro944FPzxwM0QTWU4tdLlfdXQcG5Z0IVS8HKTXoWxEeALAXkPd5PNMkNMQVC7dTiFM+N0v9XcYmDt4QRiPRhDxD1U1t81f9Opqqzr7WR+3BpAPeyeB23ibcvxo5GKqoO7l4b4Q2/5bNM+ihZtKrXNukAXo7jmwf8izBdK7WCo3D7UZduXPjanlA8736DU14T7Qljr1spLqzNKL7CiY5jf99Xs7O3b+cIuhRdxSJ7OX3zBmWHPmqWzIbkPlEypZCw9J8XGrbB1itMWQmtxiPfbrmHiTGxf1Obcf9cXv4++x2De/UFx2Nfb/sq8skmo5PUpCMM20AqL0ZqMdCdpXwXmowklV/ohLfsi7fZ2v4pBIE86zwLzL8FgxCN5ngAcpjSoOZv6GAZG9sXMGyw4K208lcOIljACN4ArOAN53i1nqTwBBwOH5U/olnBgQxk5Zo7EU9ZbkHfWj4x9nmZfIBltXXuRLaZLQdHNapRkKu5CNdEzv5KTyxB8d+aSiQXS4l19/LFExjoewOHvnYnwgbUbuNJ4yt9YGzJBIds+MiG25dC3Jp+wv2Gu3TqxIQ=
after_success:
- bash deploy.sh
